// <auto-generated />
using System;
using KaydenMiller.TableTop.LootTableGenerator.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaydenMiller.TableTop.LootTableGenerator.Infrastructure.Migrations
{
    [DbContext(typeof(LootTableGeneratorDbContext))]
    [Migration("20230902003527_AddDescriptorNameColumn")]
    partial class AddDescriptorNameColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("KaydenMiller.TableTop.LootTableGenerator.Domain.DescriptorAggregate.Descriptor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("_availableLootIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AvailableLootIds");

                    b.Property<string>("_modifierIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ModifierIds");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Descriptors");
                });

            modelBuilder.Entity("KaydenMiller.TableTop.LootTableGenerator.Domain.EquipmentAggregate.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("KaydenMiller.TableTop.LootTableGenerator.Domain.LootAggregate.Loot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("_equipmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("EquipmentId");

                    b.Property<int>("_maxQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaxQuantity");

                    b.Property<int>("_minQuantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MinQuantity");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<float>("_rarity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.5f)
                        .HasColumnName("RarityPercentage");

                    b.HasKey("Id");

                    b.ToTable("Loot");
                });

            modelBuilder.Entity("KaydenMiller.TableTop.LootTableGenerator.Domain.ModifierAggregate.Modifier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("_maxQuantityModifier")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaxQuantityModifier");

                    b.Property<int>("_minQuantityModifier")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MinQuantityModifier");

                    b.Property<string>("_name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<float>("_quantityMultiplier")
                        .HasColumnType("REAL")
                        .HasColumnName("QuantityMultiplier");

                    b.HasKey("Id");

                    b.ToTable("Modifiers");
                });

            modelBuilder.Entity("KaydenMiller.TableTop.LootTableGenerator.Domain.RoomAggregate.LootTable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("_descriptorIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("DescriptorIds");

                    b.Property<string>("_modifierIds")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ModifierIds");

                    b.HasKey("Id");

                    b.ToTable("LootTables");
                });
#pragma warning restore 612, 618
        }
    }
}
